### ISSUE TITLE
Структура БД

### ISSUE THREAD

**Issue by ocassio** [ncedu-tlt/social-network#4]

**Comment by GlebsIT** [comment]
![bd](https://user-images.githubusercontent.com/27953767/36683949-67e0101a-1b38-11e8-8495-cc0bd46d0a04.png)
Скидываем первые наработки.

**Comment by GlebsIT** [comment]
могу расшарить если нужно.http://dbdesigner.net.

**Comment by ocassio** [comment]
@GlebsIT Да, было бы неплохо иметь постоянный доступ к последней версии.

**Comment by ocassio** [comment]
\+ @IngerGodal

**Comment by GlebsIT** [comment]
![default](https://user-images.githubusercontent.com/27953767/37052810-daa3ca36-2193-11e8-85a2-badc6cc31c8c.png)

**Comment by GlebsIT** [comment]
приложил актуальный скрин структуры БД.
